volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"
  
  backend:
    image: nrmously/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    env_file: .env
    image: nrmously/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend
  
  gateway:
    image: nrmously/foodgram_gateway
    ports:
      - "9500:80"
    volumes:
      - static:/staticfiles/
      - media:/media
    depends_on:
      - backend
      - frontend